### ISSUE TITLE
Service Name Not Appearing in Person Page

### ISSUE THREAD

**Issue by cyramic** [SocialFinanceDigitalLabs/family-context-live#60]
In the Demo, in the "Details of service involvements" section, for some reason the service name wasn't appearing in the table. This was when using the FC test data and loading into the database.

![image](https://github.com/SocialFinanceDigitalLabs/family-context-live/assets/25739674/cf81fa7e-4a4e-42e4-ae86-fb6275cf2444)

**Comment by cyramic** [comment]
@tab1tha This is related to the other one, but when I load multiple CSVs with the same data_intake command it stores the foldername as part of the service name.   See this:

![image](https://github.com/SocialFinanceDigitalLabs/family-context-live/assets/25739674/c03d1830-f9d2-4ea5-8152-859af96a331a)

Could you update the bit that parses the service name to be the service name to be only the file name and not the path as well?  Thanks!

**Comment by tab1tha** [comment]
String methods were used to get the filename from the filepath and it was hardcoded to split on \ (windows paths).
The changes in the pull request that is attached replace that line with pathlib parsing so that both / and \ paths are processed. 
Looking into the absent service names bug now.

**Comment by tab1tha** [comment]
The service names show on my end. 
It is possible that they were not rendered earlier due to the parsing issue. Since that is resolved, do check if it works now.
<img width="614" alt="image" src="https://github.com/SocialFinanceDigitalLabs/family-context-live/assets/42181805/365f9553-5734-408d-be17-51617caa621e">
