### ISSUE TITLE
Person Page Service List Not Appearing

### ISSUE THREAD

**Issue by cyramic** [SocialFinanceDigitalLabs/family-context-live#62]
When loading multiple data sets from the fake data, the table/list of services wasn't populating entirely.

1 Data Set:  All services were listed along with "No Records Available"
2 Data Sets: Only the first service was listed in the table. The others disappeared.

![image](https://github.com/SocialFinanceDigitalLabs/family-context-live/assets/25739674/b18fa4c2-375d-47c8-9001-60db53acbd52)

**Comment by cyramic** [comment]
It seems like the DataSource table isn't being populated...

![image](https://github.com/SocialFinanceDigitalLabs/family-context-live/assets/25739674/c8a95dd3-df0b-4957-ac74-b91ada4a7ab6)

**Comment by cyramic** [comment]
One thing that may be causing this is on the following line:

https://github.com/SocialFinanceDigitalLabs/family-context-live/blob/726a9c5c3073bf50fe6e0a4058ec2556a49798b6/core/management/commands/data_intake.py#L55

We are importing multiple files, and this deletes all records before each.  The delete functions should be moved to a different command instead of being in the data intake.

**Comment by tab1tha** [comment]
It seems to work fine on my end. 
This is the DataSource Table showing the updates done yesterday when the Faker region was changed.
<img width="404" alt="image" src="https://github.com/SocialFinanceDigitalLabs/family-context-live/assets/42181805/227ce9f4-fe69-4832-aebc-6de80b55a5b7">

Also, I am able to access the objects from the shell.
<img width="425" alt="image" src="https://github.com/SocialFinanceDigitalLabs/family-context-live/assets/42181805/cd4a76d4-2a52-441c-b442-19050d789729">

**Comment by cyramic** [comment]
Strange. Not sure why it's not working in production. It didn't work in the demo, and I was able to replicate in my own environment.

**Comment by tab1tha** [comment]
Oh that explains it.
Then it's a good idea to get those delete statements out of the data_intake command.
I'll get it done.

**Comment by cyramic** [comment]
Thanks!  I was able to fix things by adding all CSVs in at the same time, so that's the issue.
