### ISSUE TITLE
Fix Heroku Deployment

### ISSUE THREAD

**Issue by cyramic** [SocialFinanceDigitalLabs/family-context-live#63]
Heroku is no longer deploying and the FC demo app will be needed to show project off.

**Comment by tab1tha** [comment]
Is this still an issue?
Heroku works on my end. 
It tends to get stuck if I leave the tab open for a while but it works when refreshed.

**Comment by tab1tha** [comment]
Oh I see. 
I was using the demo: https://family-context-demo.herokuapp.com/
