### ISSUE TITLE
[Housekeeping] Code formatting

### ISSUE THREAD

**Issue by tab1tha** [SocialFinanceDigitalLabs/family-context-live#75]
I would like to create a pull request of little things that I wanted to change but didn't fit in whatever pull request I was working on at the time.

- [ ] add prettify/djlint and format all html documents.
- [x] redirect the pre-commit hook config so that flake8 is gotten from gitlab and not github. The gitlab sign in doesn't seem to work. Then again, can we totally remove the flake8 hook? isort and black do a good job. 
- [x] run black on everything. The hitches with the pre-commit hook mean that there are probably files from my end which need to be reformated.
- [ ] Remove unused files such as `person_relations.html`
- [x] remove the static folder from git tracking.

These can be split across commits in the same pull request or made into multiple small PRs.

**Comment by cyramic** [comment]
I'd prefer smaller PRs if possible, but these are all good calls.

**Comment by tab1tha** [comment]
It's possible. 
I'll split them up.
